server:
  port: 1024
  servlet:
    context-path: /everday

mybatis:
  mapper-locations: classpath:day/crease/day/mapper/**/*/xml
  configuration:
    call-setters-on-nulls: true

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true
    password: root123
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource




